import * as uriBuilder from "../uriBuilder";

it("should return true", () => {
  expect(
    uriBuilder.qrValueBuilder(
      "347N1Thc213QqfYCz3PZkjoJpNv5b14kBd",
      "BTC",
      "300"
    )
  ).toStrictEqual("bitcoin:347N1Thc213QqfYCz3PZkjoJpNv5b14kBd?amount=300");

  expect(
    uriBuilder.qrValueBuilder("347N1Thc213QqfYCz3PZkjoJpNv5b14kBd", "BTC.B")
  ).toStrictEqual("347N1Thc213QqfYCz3PZkjoJpNv5b14kBd?amount=0");

  expect(
    uriBuilder.qrValueBuilder(
      "This is supposed to be generated by the backend.",
      "100",
      "DummyCoin"
    )
  ).toStrictEqual("");
});
